### ISSUE TITLE
If vac is 0.0, this line results in a division by zero

### ISSUE THREAD

**Issue by padriaanse** [jbouwh/omnikdatalogger#10]
https://github.com/jbouwh/omnikdatalogger/blob/a1dc1e3e7edbd6d5e93847752f3c254f1e7e099c/apps/omnikdatalogger/omnik/InverterMsg.py#L109

**Comment by jbouwh** [comment]
You are right. The test should be vac > 0. If pac>0 then vac should also be >0 but withe the solarman pv client no vac attribute will be available.
