### ISSUE TITLE
Can't add omnik in HACS and the new version of HACS does not have an automation menu.

### ISSUE THREAD

**Issue by bright72** [jbouwh/omnikdatalogger#13]

**Comment by jbouwh** [comment]
I am using HACS 1.15.2 and all works as designed. May be you need to restart or refresh your browser. Further, make sure you have installed the AppDaemon Addon. Without it you will not be able to run AppDaemon or NetDeamon.

**Comment by jbouwh** [comment]
Closing here. Please let me know if this is not helping.

**Comment by bright72** [comment]
![Screen Shot 2564-09-18 at 01 02 21](https://user-images.githubusercontent.com/3614430/133833764-6363c830-ac85-47c9-8296-63eae58eed8a.png)

**Comment by jbouwh** [comment]
You do not need to add it as a custom integration. It is an automation and it is pre installed. The category is AppDaemon

https://github.com/jbouwh/omnikdatalogger/wiki/Install-using-HACS-(Home-Assistant-Community-Store)#install-omnik-datalogger-using-hacs
I have added a note about the requirement of the installation of the AppDaemon4 addon.

**Comment by bright72** [comment]
I have already configured and install AppDaemon 4. Why search not found.

<img width="887" alt="Screen Shot 2564-09-18 at 13 02 38" src="https://user-images.githubusercontent.com/3614430/133878156-62565d3a-960b-4315-abba-4e32b4a2b540.png">

<img width="921" alt="Screen Shot 2564-09-18 at 13 10 33" src="https://user-images.githubusercontent.com/3614430/133878276-d23f1c2b-c460-464a-86ec-4c4d12ad8ed8.png">

<img width="924" alt="Screen Shot 2564-09-18 at 13 06 42" src="https://user-images.githubusercontent.com/3614430/133878190-70f7cbd5-4bc7-4bd0-a203-cabb0e1fbcf3.png">

**Comment by jbouwh** [comment]
Did you install AppDaemon4 before you installed HACS?
https://hacs.xyz/docs/categories/appdaemon_apps/

**Comment by bright72** [comment]
Thank you it helps me so much.
