### ISSUE TITLE
Make DSMR entities compliant with new Home Assistant "Energy" module

### ISSUE THREAD

**Issue by serrj-sv** [jbouwh/omnikdatalogger#3]
Latest Home Assistant  introduced new [Energy Grid](https://www.home-assistant.io/docs/energy/electricity-grid/) module. But DSMR entities produced by "omnikdatalogger" does not apper in the list of "Consumed Energy" entities list

![2021-08-05_13-02](https://user-images.githubusercontent.com/51411734/128339867-3070a89d-8a29-43f8-a81f-5af7cf7d8f5a.png)

I'm running the lates version (v1.6.4) of omnikdatalogger 

Also couple of suggestions:
1. disable polling omnik inverter in tcpclient mode from dusk to dawn to not spam the log
2. keep updating "combined DSMR" entities event if there is no updates coming from Inverter.

Anyway, thanks for amazing tool, I really enjoy it!!

**Comment by jbouwh** [comment]
Did you install release 1.6.4?
There were some fixes.

**Comment by serrj-sv** [comment]
yep. latest version installed

**Comment by serrj-sv** [comment]
this is strange, because in dev. tools I can see all necessery attributes (device_class: energy and state_class: measurement)

**Comment by jbouwh** [comment]
I've got it working myself

**Comment by serrj-sv** [comment]
Oh.. indeed, it looks like I was running  old version of omnikdatalogge. Just received an update notification in HACS!

**Comment by serrj-sv** [comment]
everything is OK now, closing
