### ISSUE TITLE
Strange behaviour of consumed energy after inverter shuts down after sunset

### ISSUE THREAD

**Issue by joost01** [jbouwh/omnikdatalogger#53]
I've noticed some strange behaviour of consumed energy after inverter shuts down after sunset.

See the attached screenshot:
![Screenshot 2021-12-06 at 17 33 09](https://user-images.githubusercontent.com/23291285/144885601-c7da9765-cc47-4362-8e93-10bc974e6881.png)

It is visible on the pvoutput.org website when you open the stats of one of the previous days. When you look at the outputs, in this case for 04-12, you see the last inverter update is at 04:35 pm. After that the used energy column changes from 6.637 to 12.720 kWh. It stays at this value until the end of the day.

I'm not sure yet if it is the omniklogger script or something in PVoutput, but another account which is provided by the dsmr entity doesn't show this behaviour

**Comment by jbouwh** [comment]
After the inverter stops generating only consumed energy is published, may be this is causing the artifact. What I can do is keep pushing the last produced energy from cache.

**Comment by joost01** [comment]
Well, in my case the problem occured for the first time when I updated the docker container. The running container was a little bit outdated (created 2020-10-02), but this one didn't have this behaviour. I've attached a screenshot.

![Screenshot 2021-12-07 at 10 09 37](https://user-images.githubusercontent.com/23291285/145000057-db3544ae-7d48-4fe3-a669-ab947fb47f9c.png)

**Comment by jbouwh** [comment]
Created a new beta release that will continue to send the generated energy from cache.

**Comment by jbouwh** [comment]
This behaviour  has not been there all the time, so hopefullly we get some better detail with this new version. If there still is a delta, then there is a possible problem in the calculation. Another theory is that pvoutput has changed it algorithm.

**Comment by jbouwh** [comment]
As it looks to me, there is something wrong with the calculation. I still see the same symptoms.

**Comment by jbouwh** [comment]
Checked again. I see the data that is published is correct. It is also publish to home_assistant as MQTT sensor, and I do not see the jump there.

**Comment by jbouwh** [comment]
![afbeelding](https://user-images.githubusercontent.com/7188918/145450357-7675cdee-4c09-4721-94ce-7350422f8560.png)
pvoutput seems to get correct data, so I cannot explain the behavior. The energy used seems to hang is some sort of way. But the pvoutput sensor (homeassistant) reports the correct energy_consumed. This is not what the graph tells.

**Comment by jbouwh** [comment]
![afbeelding](https://user-images.githubusercontent.com/7188918/145450915-046a6fa6-a7d7-4f2a-aa1b-7d1ea92c56a9.png)

**Comment by jbouwh** [comment]
This is while not sending generated energy. Some how it then uses the time stamp of the last generated energy data. All datapoints are raised together, but the total energy is correct.
![afbeelding](https://user-images.githubusercontent.com/7188918/145454981-a36ee2b9-b38a-40d8-bb2f-adf6eda7bc80.png)
5 minutes later:
![afbeelding](https://user-images.githubusercontent.com/7188918/145455482-f846a540-a537-4059-b60c-5c5fa4412d0a.png)

**Comment by jbouwh** [comment]
Somehow there is a duplicate upload, that uses the last solar timestamp. Will sort this out later.
```
2021-12-10 16:20:12.308665 INFO omnikdatalogger: pvoutput upload: {'d': '20211210', 't': '15:48', 'c1': 1, 'v3': '12930738.000', 'v4': '396.000', 'v1': '610.00', 'v2': '0', 'v6': 232.0}
2021-12-10 16:20:11.701746 INFO omnikdatalogger: Combining cached logging for plant 953  with DSRM data.
2021-12-10 16:20:11.698968 INFO omnikdatalogger: pvoutput upload: {'d': '20211210', 't': '16:20', 'c1': 1, 'v3': '12930738.000', 'v4': '396.000', 'v1': '610.00', 'v2': '0', 'v6': 232.0}
2021-12-10 16:20:11.104854 INFO omnikdatalogger: Net data update for plant 953 UTC 2021-12-10 15:20:08+00:00
2021-12-10 16:18:32.331497 INFO omnikdatalogger: pvoutput upload: {'d': '20211210', 't': '15:48', 'c1': 1, 'v3': '12930727.000', 'v4': '405.000', 'v1': '610.00', 'v2': '0', 'v6': 233.0}
2021-12-10 16:18:31.728129 INFO omnikdatalogger: Combining cached logging for plant 953  with DSRM data.
2021-12-10 16:18:31.725301 INFO omnikdatalogger: pvoutput upload: {'d': '20211210', 't': '16:18', 'c1': 1, 'v3': '12930727.000', 'v4': '405.000', 'v1': '610.00', 'v2': '0', 'v6': 233.0}
```

**Comment by jbouwh** [comment]
I think I have solved the the issue now, and released a new beta. I'll let it run for some time to see if this is working correctly now.

**Comment by jbouwh** [comment]
New release and fix docker version should solve the issue.

**Comment by joost01** [comment]
I've downloaded the latest image, if I notice any strange behaviour I'll let you know. Thank you again voor the quick response!

**Comment by joost01** [comment]
For the last two days the data on PVOutput was as expected! Problem solved, ticket can be closed.
