### ISSUE TITLE
docker run --rm --serialnumber

### ISSUE THREAD

**Issue by lukasmedia** [jbouwh/omnikdatalogger#60]
The example:

`docker run --rm --serialnumber NLDN123456789012 --listenaddress 0.0.0.0 --omniklogger 176.58.117.69 --omnikloggerport 10004`

The ouptput: 

```
unknown flag: --serialnumber
See 'docker run --help'.

```

**Comment by jbouwh** [comment]
Hi, omnikdatalogger does not accept a serial number from the the command line like omnikdataloggerproxy. Please place your config in a yaml file and configure client type and output module.

**Comment by jbouwh** [comment]
For more info about docker see:
https://github.com/jbouwh/omnikdatalogger/tree/main/docker
