### ISSUE TITLE
connection to logger with SN 178**** / inverter SN 234**** failing

### ISSUE THREAD

**Issue by muppel2** [jbouwh/omnikdatalogger#83]
Hello Jan,

I have to tried to configure your tool to for use with my LSW3 datalogger, but unfortunately encounter an error message when using the tcpclient:
`INFO:omnik.datalogger:I 2022-11-07T14:00:42.527266 Using configured data configuration from '/home/pi/omnikdatalogger/apps/omnikdatalogger/data_fields.json'.`
`INFO:omnik.datalogger:I 2022-11-07T14:00:42.527926 Using energy cache file './persistant_cache.json'.`
`INFO:omnik.datalogger:I 2022-11-07T14:00:42.552706 Initializing client : tcpclient.`
`INFO:omnik.datalogger:I 2022-11-07T14:00:42.554804 Client enabled: TCPclient`
`INFO:omnik.datalogger:I 2022-11-07T14:00:42.555128 Output plugins configured: ['influxdb'].`
`INFO:__main__:I 2022-11-07T14:00:42.575398 Daemon interval 360 seconds.`
`ERROR:omnik.datalogger:E 2022-11-07T14:00:43.577822 Unexpected error during data handling: '2746864'`
`INFO:__main__:I 2022-11-07T14:00:49.584578 Stopping Omnikdatalogger...`

I am not sure if my hardware is supported yet?
logger_sn: 178****
inverter_port: 8899
inverter_sn: 234**** resp. SP1ES108***

Logger firmware: LSW3_15_270A_1.50

Thanks in advance
Sebastian

**Comment by jbouwh** [comment]
Sorry for the late answer. Not sure your logger is compatible, Closing this issue as it is stale now.
